# Generated by Django 3.2.1 on 2023-02-15 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='第x次周赛', max_length=128)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('over_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebugRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, default='', max_length=8388608)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=8388608)),
            ],
        ),
        migrations.CreateModel(
            name='FileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', models.BooleanField(default=False)),
                ('request_path', models.URLField(default='', max_length=128)),
                ('content', models.TextField(blank=True, default='', max_length=8192)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.CharField(blank=True, default='', max_length=100)),
                ('difficulty', models.CharField(choices=[('简单', '简单'), ('中等', '中等'), ('困难', '困难')], default='简单', max_length=20)),
                ('time_limit', models.IntegerField(choices=[(1, 1), (2, 2), (5, 5)], default=1)),
                ('space_limit', models.IntegerField(choices=[(64, 64), (128, 128), (512, 512)], default=64)),
                ('submit_nums', models.IntegerField(default=0)),
                ('ac_nums', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('ZCOJ', 'ZCOJ'), ('Acwing', 'AcWing'), ('洛谷', '洛谷'), ('Codeforces', 'Codeforces')], default='ZCOJ', max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=262144)),
                ('input_format', models.TextField(blank=True, default='', max_length=131072)),
                ('output_format', models.TextField(blank=True, default='', max_length=131072)),
                ('data_range', models.TextField(blank=True, default='', max_length=32768)),
                ('input_example', models.TextField(blank=True, default='', max_length=32768)),
                ('output_example', models.TextField(blank=True, default='', max_length=32768)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubmitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0)),
                ('problem_id', models.IntegerField(blank=True, default=0)),
                ('language', models.CharField(blank=True, default='C++', max_length=64)),
                ('code', models.TextField(blank=True, default='', max_length=8388608)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contest_id', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='视频题解', max_length=64)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_video', to='Backend.file')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_videos', to='Backend.problem')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forbidden', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(default='Trainee', max_length=64)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=16)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('level', models.IntegerField(default=1)),
                ('record', models.TextField(default='', max_length=1024)),
                ('address', models.CharField(default='中国', max_length=1024)),
                ('photo', models.URLField(blank=True, default='https://app2105.acapp.acwing.com.cn/media/profile/default.jpg', max_length=256)),
                ('followings', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='题解', max_length=64)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_solution', to='Backend.file')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_solutions', to='Backend.problem')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_participant', to='Backend.contest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_participatant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('parentId', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, default='', max_length=8388608)),
                ('likes', models.IntegerField(default=0)),
                ('address', models.CharField(default='中国', max_length=1024)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_comments', to='Backend.file')),
            ],
            options={
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2048, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_send_message', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receive_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='ChatList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receive_list', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_send_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='题解', max_length=64, null=True)),
                ('tags', models.CharField(default='', max_length=128, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_blog', to='Backend.file')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
