# Generated by Django 3.2.1 on 2023-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.CharField(blank=True, default='', max_length=100)),
                ('difficulty', models.CharField(choices=[('简单', '简单'), ('中等', '中等'), ('困难', '困难')], default='简单', max_length=20)),
                ('limit', models.CharField(choices=[('1s/64M', '1s/64M'), ('2s/128M', '2s/128M'), ('5s/512M', '5s/512M')], default='1s/64M', max_length=20)),
                ('source', models.CharField(choices=[('ZCOJ', 'ZCOJ'), ('Acwing', 'AcWing'), ('洛谷', '洛谷'), ('Codeforces', 'Codeforces')], default='ZCOJ', max_length=30)),
                ('decription', models.TextField(blank=True, default='', max_length=131072)),
                ('input_format', models.TextField(blank=True, default='', max_length=32768)),
                ('data_range', models.TextField(blank=True, default='', max_length=32768)),
                ('input_example', models.TextField(blank=True, default='', max_length=32768)),
                ('output_format', models.TextField(blank=True, default='', max_length=32768)),
            ],
        ),
    ]
