# Generated by Django 3.2.1 on 2023-02-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='xxx',
            field=models.TextField(default='x', max_length=20),
        ),
    ]
