# Generated by Django 3.2.1 on 2023-02-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_problem_xxx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='xxx',
        ),
        migrations.AddField(
            model_name='problem',
            name='contest_id',
            field=models.IntegerField(default=0),
        ),
    ]
