# Generated by Django 3.2.1 on 2023-02-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20230215_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='contest_id',
            new_name='contest',
        ),
    ]
