# Generated by Django 3.2.1 on 2023-01-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_problem_output_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='decription',
            new_name='description',
        ),
    ]
