# Generated by Django 3.2.1 on 2023-02-15 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend', '0004_rename_contest_id_problem_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_standing', to='Backend.contest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_standing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_discussion', to='Backend.contest')),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_contest_discussion', to='Backend.file')),
            ],
        ),
    ]
