# Generated by Django 3.2.1 on 2023-01-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_rename_decription_problem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, default='', max_length=8388608)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
