# Generated by Django 3.2.1 on 2023-01-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_judgerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgerecord',
            name='status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
