# Generated by Django 3.2.1 on 2023-02-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_contestdiscussion_conteststanding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
