# Generated by Django 3.2.1 on 2023-01-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_judgerecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, default='', max_length=8388608)),
            ],
        ),
        migrations.RenameModel(
            old_name='JudgeRecord',
            new_name='SubmitRecord',
        ),
    ]
