# Generated by Django 3.2.1 on 2023-02-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20230216_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
