# Generated by Django 3.2.1 on 2023-02-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_auto_20230216_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestparticipant',
            options={'ordering': ['-score', 'penalty']},
        ),
        migrations.DeleteModel(
            name='ContestStanding',
        ),
    ]
