# Generated by Django 3.2.1 on 2023-01-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_auto_20230131_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ac_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='submit_nums',
            field=models.IntegerField(default=0),
        ),
    ]
