# Generated by Django 3.2.1 on 2023-02-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_auto_20230131_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.IntegerField(default=1)),
                ('space_limit', models.IntegerField(default=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
