# Generated by Django 3.2.1 on 2023-02-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_acproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sno',
            field=models.CharField(default='', max_length=64),
        ),
    ]
