# Generated by Django 3.2.1 on 2023-02-22 09:10

from django.db import migrations
import simplepro.editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_userinfo_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=simplepro.editor.fields.MDTextField(blank=True, default='', max_length=262144),
        ),
    ]
