# Generated by Django 3.2.1 on 2023-02-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_problem_test_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_case',
        ),
    ]
