# Generated by Django 3.2.1 on 2023-02-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_auto_20230201_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='limit',
            field=models.CharField(choices=[('1', '1s/64M'), ('2', '2s/128M'), ('3', '5s/512M')], default='1', max_length=20),
        ),
    ]
