# Generated by Django 3.2.1 on 2023-02-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('关注了我', '关注了我'), ('评论了我', '评论了我')], default='关注了我', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='record',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sno',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
