# Generated by Django 3.2.1 on 2023-02-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_alter_problem_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='limit',
        ),
    ]
