# Generated by Django 3.2.1 on 2023-02-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_remove_problem_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (5, 5)], default=1),
        ),
    ]
