# Generated by Django 3.2.1 on 2023-02-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_auto_20230223_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('关注了', '关注了'), ('评论了', '评论了')], default='关注了我', max_length=32),
        ),
    ]
