# Generated by Django 3.2.1 on 2023-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_problem_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='show',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='space_limit',
            field=models.IntegerField(choices=[(64, 64), (128, 128), (512, 512)], default=64),
        ),
    ]
