# Generated by Django 3.2.1 on 2023-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_auto_20230201_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitrecord',
            name='language',
            field=models.CharField(blank=True, default='C++', max_length=64),
        ),
        migrations.AddField(
            model_name='submitrecord',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submitrecord',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
