# Generated by Django 3.2.1 on 2023-03-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_auto_20230304_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='rating',
            field=models.IntegerField(default=1500),
        ),
    ]
