# Generated by Django 3.2.1 on 2023-03-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_userinfo_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='contest',
            name='clear',
            field=models.BooleanField(default=False),
        ),
    ]
