# Generated by Django 3.2.1 on 2023-02-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_alter_submitrecord_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitrecord',
            name='problem_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='submitrecord',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
