# Generated by Django 3.2.1 on 2023-02-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_auto_20230202_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitrecord',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
