# Generated by Django 3.2.1 on 2023-02-02 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_alter_submitrecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitrecord',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
