# Generated by Django 3.2.1 on 2023-02-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_auto_20230203_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='background',
            field=models.URLField(blank=True, default='http://106.15.183.53:8000/static/images/default_user_space_background', max_length=256),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.URLField(blank=True, default='http://106.15.183.53:8000/static/images/default_user_profile', max_length=256),
        ),
    ]
