# Generated by Django 3.2.1 on 2023-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0024_auto_20230203_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='background',
            field=models.URLField(blank=True, default='http://106.15.183.53:8000/static/images/default_user_space_background.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.URLField(blank=True, default='http://106.15.183.53:8000/static/images/default_user_profile.jpg', max_length=256),
        ),
    ]
