# Generated by Django 3.2.1 on 2023-02-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0025_auto_20230203_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admirer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='Trainee', max_length=64),
        ),
    ]
