# Generated by Django 3.2.1 on 2023-02-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0027_userinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
