# Generated by Django 3.2.1 on 2023-02-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0030_auto_20230204_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='background',
        ),
    ]
