# Generated by Django 3.2.1 on 2023-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0033_auto_20230204_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
