# Generated by Django 3.2.1 on 2023-02-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0034_auto_20230204_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='followings',
            field=models.IntegerField(default=0),
        ),
    ]
