# Generated by Django 3.2.1 on 2023-02-05 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0035_auto_20230204_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=16),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.URLField(blank=True, default='http://106.15.183.53:8000/media/profile/default.jpg', max_length=256),
        ),
    ]
