# Generated by Django 3.2.1 on 2023-02-06 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0036_auto_20230205_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.URLField(blank=True, default='https://app2105.acapp.acwing.com.cn/media/profile/default.jpg', max_length=256),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='题解', max_length=64)),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, default='', max_length=8388608)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_solutions', to='Backend.problem')),
            ],
        ),
    ]
