# Generated by Django 3.2.1 on 2023-02-06 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0037_auto_20230206_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
