# Generated by Django 3.2.1 on 2023-02-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0039_auto_20230207_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='content',
        ),
    ]
