# Generated by Django 3.2.1 on 2023-02-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0040_remove_solution_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_solution', to='Backend.file'),
        ),
    ]
