# Generated by Django 3.2.1 on 2023-02-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0041_alter_solution_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-create_time']},
        ),
    ]
