# Generated by Django 3.2.1 on 2023-02-08 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0045_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='address',
            field=models.CharField(default='来自中国', max_length=1024),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, default='', max_length=8388608),
        ),
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
