# Generated by Django 3.2.1 on 2023-02-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0046_auto_20230208_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='中国', max_length=1024),
        ),
    ]
