# Generated by Django 3.2.1 on 2023-02-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0048_userinfo_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
