# Generated by Django 3.2.1 on 2023-02-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0049_alter_userinfo_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-createTime']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parentId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='comment',
            name='address',
            field=models.CharField(default='中国', max_length=1024),
        ),
    ]
