# Generated by Django 3.2.1 on 2023-02-11 03:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0050_auto_20230209_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='视频题解', max_length=64)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_video', to='Backend.file')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_videos', to='Backend.problem')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
