# Generated by Django 3.2.1 on 2023-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0052_chatlist_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['create_time']},
        ),
        migrations.AlterField(
            model_name='chatlist',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
