# Generated by Django 3.2.1 on 2023-02-12 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0053_auto_20230212_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlist',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
