# Generated by Django 3.2.1 on 2023-02-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0054_alter_chatlist_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='read',
        ),
    ]
