# Generated by Django 3.2.1 on 2023-02-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0055_remove_chatmessage_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlist',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
